### ISSUE TITLE
FVCOM netcdf files - error reading multiple files

### ISSUE THREAD

**Issue by lgaravelli** [ichthyop/ichthyop#66]
Hello,
Ichthyop runs without issues with one file but there is an error when it tries to open a second file:
ichthyop[info] Step 1380 / 2880
ichthyop[info] Reading NetCDF variables...
ichthyop[info] Saving variables...
ichthyop[info] Step 1381 / 2880 (Time 2017-01-02T00:00)
ichthyop[severe] Index -999 out of bounds for length 25019 | java.lang.ArrayIndexOutOfBoundsException: Index -999 out of bounds for length 25019
ichthyop[severe] [Simulation] Initialisation failed

Beginning of simulation is year 2017 month 01 day 01 at 01:00

Thank you for your help,
Lysel

**Comment by barriern** [comment]
Hi @lgaravelli 

Could you please send me your configuration file? I will try to have a look.

Thanks

@barriern

**Comment by barriern** [comment]
And eventually could you try to run Ichthyop from the `Cmd` prompt or from the Terminal? In order to have more informations about the error.

**Comment by lgaravelli** [comment]
Hello,
see my config file attached. I copied below the error message. Thank you for your help!
Lysel
[cfg-fvcom.xml.txt](https://github.com/ichthyop/ichthyop/files/11379214/cfg-fvcom.xml.txt)

ichthyop[info] Step 1380 / 2880
ichthyop[info] Reading NetCDF variables...
ichthyop[info] Saving variables...
ichthyop[severe] An error occured while running the simulation | java.lang.ArrayIndexOutOfBoundsException: Index -999 out of bounds for length 25019
  org.previmer.ichthyop.dataset.FvcomDataset.getXBarycenter(FvcomDataset.java:1148)
  org.previmer.ichthyop.dataset.FvcomDataset.getDepth(FvcomDataset.java:497)
  org.previmer.ichthyop.dataset.FvcomDataset.z2depth(FvcomDataset.java:273)
  org.previmer.ichthyop.GridPoint.grid2Geo(GridPoint.java:148)
  org.previmer.ichthyop.action.SysActionMove.execute(SysActionMove.java:76)
  org.previmer.ichthyop.manager.ActionManager.executeActions(ActionManager.java:151)
  org.previmer.ichthyop.particle.Particle.step(Particle.java:162)
  org.previmer.ichthyop.Population.step(Population.java:131)
  org.previmer.ichthyop.Simulation.step(Simulation.java:64)
  org.previmer.ichthyop.IchthyopBatch.run(IchthyopBatch.java:103)
  java.base/java.lang.Thread.run(Thread.java:833)

**Comment by barriern** [comment]
Hi @lgaravelli 

Could you please send me your `fvcom_EGC_zones.xml` file? Thanks

@barriern

**Comment by lgaravelli** [comment]
[fvcom_EGC_zones.xml.txt](https://github.com/ichthyop/ichthyop/files/11500049/fvcom_EGC_zones.xml.txt)

here you go, thanks for the reminder to send this! And thanks again for your help.

**Comment by barriern** [comment]
Hi again @lgaravelli 

I think the error is related to the Zone file. The enclosed file seems to work, but yours return the error you showed in the above. I will have a look

[fvcom_zones.xml.txt](https://github.com/ichthyop/ichthyop/files/11500434/fvcom_zones.xml.txt)

@barriern

**Comment by lgaravelli** [comment]
Sorry, I sent you the wrong file. However, I have been trying with one zone and still have the same error. It happens when Ichthyop starts to read the second FVCOM .nc file. I attached everything here.

**Comment by barriern** [comment]
Hi @lgaravelli 

I would need them if possible. Because I tested by duplicating one file and it worked. Maybe a google drive or something similar?

@barriern

**Comment by lgaravelli** [comment]
Hi @barriern 
I sent you a link to access the nc files. Thanks a lot!

**Comment by barriern** [comment]
Hi @lgaravelli 

It was a bug in the computation of depth. When a particle is on land, it is not included in any of the grid triangle, hence the error. I have made a slight modification of the code so that depth is NaN when the particle is on land. It seems to work.

Here is a link to the corrected Jar file:

https://filesender.renater.fr/?s=download&token=bcf8f521-9064-4c7f-a831-10d151ca5d4e

Please tell me if it solves the issue.

Cheers 

@barriern

**Comment by lgaravelli** [comment]
@barriern it is working now! Thank you very much for looking into this, I really appreciate it.
Cheers,
Lysel

**Comment by lmengel422** [comment]
Hello @barriern,
I am continuing the work mentioned in this issue (#66) with @lgaravelli. While your fix stopped the error messages and the simulation runs completely, the ICHTHYOP output files only contain lon and lat results for 1 day. After 1 day the values are NaN. We think ICHTHYOP is not advancing/reading the multiple FVCOM input netcdf files (1 per day) during the simulation. Or perhaps something else is going on?
Thanks,
@lmengel422

**Comment by barriern** [comment]
Hi @lmengel422 

I have reopened the issue. Indeed it is very weird, it seems that the particles all beached when the new file is loaded.

I will try to investigate 

@barriern

**Comment by lmengel422** [comment]
Hi @barriern,

Thank you very much! If it helps, it does not look like the particles are beached on the trajectory maps... but I suppose the code is interpreting them that way. 

![image](https://github.com/ichthyop/ichthyop/assets/54828489/28c1d14b-e359-42b3-9e18-a0c8dbf41b66)

Best,
@lmengel422

**Comment by barriern** [comment]
Hi @lmengel422 

I have found the issue. It was due to a problem in reading the time variables, which induced a `NaN` value in the time-interpolation of the forcings.

I have now corrected this bug. You will find the new `.jar` here:

https://filesender.renater.fr/?s=download&token=b43984e4-47b3-40da-8270-13fa1cf36e50

Note that since the time is more precisely managed, the `initial_time` might need to be updated in your configuration file. For instance, I tried with `year 2017 month 01 day 01 at 09:00` and it seems to work.

Please let me know if you have issue.

**Comment by lmengel422** [comment]
@barriern,

Great, thank you so so much! I look forward to getting to know ICHTHYOP more.

Thanks again,
@lmengel422

**Comment by lmengel422** [comment]
Hi @barriern,

Unfortunately we are still having issues. If I start the simulation at 0900 and allow it to run for 15 hours only, it is successful because it only has to read one .nc file. As soon as I increase the transport duration beyond 15 hours, and it therefore needs to read another .nc file, it gets through the preview stage, but crashes during the simulation. Here are the error messages I am getting:

ichthyop[info] [Simulation] Run 1 / 1
ichthyop[info] [Simulation] Initialising...
ichthyop[info] {Dataset} Open G:\Lily\Ichthyop_SSM\SSM_low_res\ssm_0001.nc
ichthyop[info] Release manager setup [OK]
ichthyop[info] Time manager setup [OK]
ichthyop[info] Instantiated action "Advanced/Biology/Recruitment/In zones"
ichthyop[info] Instantiated action "Advanced/Transport/Advection"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionAgeMonitoring"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionMove"
ichthyop[info] Action manager setup [OK]
ichthyop[info] Output manager setup [OK]
ichthyop[info] {Dataset} Open G:\Lily\Ichthyop_SSM\SSM_low_res\ssm_0001.nc
ichthyop[info] Reading NetCDF variables...
ichthyop[info] Release manager initialization [OK]
ichthyop[info] Time manager initialization [OK]
ichthyop[info] Zone manager initialization [OK]
ichthyop[info] Output manager initialization [OK]
ichthyop[info] Output manager initialization [OK]
ichthyop[info] [Simulation] Initialisation [OK]
ichthyop[info] Reading NetCDF variables...
ichthyop[info] Release event (ReleaseManager) time = 3692250000 seconds. Released 10 particles.
ichthyop[info] Saving variables...
ichthyop[info] Step 1 / 2340 (Time 2017-01-01T09:00)
ichthyop[severe] null | java.lang.ArrayIndexOutOfBoundsException
ichthyop[severe] [Simulation] Initialisation failed

I will share a link to two .nc files (representing jan 01 2017 and jan 02 2017) to you so you can see how they are connecting. (These are from a lower FVCOM resolution than what @lgaravelli provided you previously. I am having the same issues with both the low and high res FVCOM files.) Thank you very much!

@lmengel422

**Comment by barriern** [comment]
Sure, please share everything I need to reproduce the error. Thanks

**Comment by lmengel422** [comment]
Hi Nicolas,
I shared the files over google drive to your email. Please let me know if you did not get them.
Lily

**Comment by barriern** [comment]
Hi @lmengel422 

I received the files. Could you also send me the Ichthyop configuration files? Thanks

Nicolas

**Comment by barriern** [comment]
Hi again @lmengel422 

I noticed that your input files are the same ones that I used. And I was able to run the model for 3 days. Please find enclosed the xml files that I used and the trajectory that I obtained.

Nicolas

[cfg-fvcom.xml.txt](https://github.com/ichthyop/ichthyop/files/12763571/cfg-fvcom.xml.txt)
[fvcom_zones.xml.txt](https://github.com/ichthyop/ichthyop/files/12763572/fvcom_zones.xml.txt)
![traj](https://github.com/ichthyop/ichthyop/assets/32549583/b4a4660a-e2b6-4645-aee2-a9f8b6bbb676)

**Comment by lmengel422** [comment]
Hi @barriern,

Wow, that looks great! That must mean there is something wrong with my config/zone files. I uploaded what I have been using in the same google drive folder. In the meantime I will play around with your files.

Thanks,
@lmengel422

**Comment by lmengel422** [comment]
Hi,

Looking through your files, the main difference seems to be that you do not have any recruitment zones. That might be where the problem lies! 

Thanks,
Lily

**Comment by barriern** [comment]
Possibly. I will have a look at it and will tell you what might be the problem.

**Comment by barriern** [comment]
Hi again Lily.

I have checked the issue and it was due, this time, to an error in the vertical interpolation process for particles close to the bottom. Now it should work, although I somehow find the trajectories a bit weird.

For practical reasons, I have published the FVCOM Ichthyop branch on the public repository: https://github.com/ichthyop/ichthyop/tree/feature/fvcom-grid

You can download the code and then compile it as described in http://documentation.ichthyop.org/start/download_ich.html#ichthyop-developers

Tell me if you have issues in doing so.

Nicolas

**Comment by lmengel422** [comment]
Hi Nicolas,

Great, thank you! I believe I successfully downloaded and compiled the code, however now I am getting this error in the preview stage:

java.lang.ClassNotFoundException: org.previmer.ichthyop.dataset.FvcomDataset

I had to download jdk 17 to get netbeans to install, perhaps that is an issue?

Thanks,
Lily

**Comment by barriern** [comment]
Hi Lily.

This error suggests that you may have downloaded the wrong branch of the code. Did you clone it?

Nicolas

**Comment by lmengel422** [comment]
Hi Nicolas, 

I did clone it. I am not really sure where I went wrong...

Funnily enough, I was able to get the last (already compiled) version of ichthyop you sent working with new zone files. Perhaps a lot of the issues are with the zone files? 

Lily

**Comment by barriern** [comment]
If you cloned it, you need to check that you are on the right branch:

```
git checkout feature/fvcom-grid
```

Then you need to recompile the code.

Nicolas

**Comment by lmengel422** [comment]
Hi Nicolas,

I think I was on that branch? At least, the output ichthyop .jar file says "FVCOM" in the main menu. Regardless, I tried again and typed in what you said and got this message:

Already on 'feature/fvcom-grid'
Your branch is up to date with 'origin/feature/fvcom-grid'.

Then I tried to build on netbeans and got this message:

Plugin org.codehaus.mojo:exec-maven-plugin:1.6.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:exec-maven-plugin:jar:1.6.0: The following artifacts could not be resolved: org.codehaus.mojo:exec-maven-plugin:pom:1.6.0 (absent): Could not transfer artifact org.codehaus.mojo:exec-maven-plugin:pom:1.6.0 from/to central (https://repo.maven.apache.org/maven2): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

Thanks,
Lily

**Comment by lmengel422** [comment]
Hi Nicolas,

I have NetBeans 19. I had to download jdk 17 to get netbeans to install (it would not work with what I had, jdk 21). I am on windows.

Thanks!
Lily

**Comment by barriern** [comment]
Hi Lily. 

I have done some updates and was able to compile and run the code using Netbeans v19 and openJDK 19.

Could you try to update the code using ``git pull`` and recompile from Netbeans?

Thanks

Nicolas

**Comment by barriern** [comment]
Hi Lily.

I have encountered this issue, but it should be solved. This is due to format issue in the Resource files (especially the é character in resource file).

On Git Bash, what do you have when you type ``git branch -vv``?

**Comment by barriern** [comment]
Ok my bad, I pushed only on the private repository, not the public one. Now you should be able to do a `git pull` and recompile. Or so I hope

**Comment by lmengel422** [comment]
I was able to do the pull this time, but netbeans still does not want to work.

Plugin org.apache.maven.plugins:maven-enforcer-plugin:3.4.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-enforcer-plugin:jar:3.4.1: The following artifacts could not be resolved: org.apache.maven.plugins:maven-enforcer-plugin:pom:3.4.1 (absent): Could not transfer artifact org.apache.maven.plugins:maven-enforcer-plugin:pom:3.4.1 from/to central (https://repo.maven.apache.org/maven2): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

I find it weird I was able to compile ichthyop that one time in the beginning but I have not been able to since... I am not sure what is going on!

**Comment by barriern** [comment]
Hi Lily.

Which version of maven do you have? I think it is a maven version issue. You are probably on v2 instead of v3.

**Comment by lmengel422** [comment]
Oh my gosh, I finally figured it out. It is because I was on the company vpn. (I am brand new here and am not used to that yet!) It finally compiled, I will now test to see if it runs. Thanks for your patience and help!

**Comment by lmengel422** [comment]
ok this build is running! Thanks again!!

**Comment by lmengel422** [comment]
Hi Nicolas!

Thanks again for your help so far.

With both the current and previous build of ichthyop, all of the particles have depths > 0 after the initial timestep. I was somehow able to get runs in which the depths were correct, but I have not been able to recreate those runs. (All of the runs that were correct I ran before October 4th, but after October 4th it is wrong.) Do you know how/why this could be happening? Does it have to do with the vertical integration fix you did? (I am confused by this idea, since I am using an ichthyop that was already compiled and it is still producing the problem.)

Best,
Lily

**Comment by barriern** [comment]
Hi Lily

I did some updates to the code. I think there was several issues regarding the vertical management of the FVCOM grid. Now it seems to run, depth seems to be quite ok. But according to the rule `be carefull of code changes done on a Friday`, I am not sure that it is definitely solved.

I let you try to do a `git pull` and recompile the code before testing again. 

I will be on holidays next week, so I won't be active a lot.

Nicolas

**Comment by lmengel422** [comment]
Hi Nicolas,

Great, thank you very much! And haha, that is a good rule to keep in mind. I will play with it and let you know of anything else I find. I hope you have a wonderful holiday!

Lily

**Comment by lmengel422** [comment]
Hi Nicolas,

Oops, now I can't get past the preview stage with that version.

ichthyop[severe] Could not retrieve parameter dataset.fvcom/field_var_bathy_triangle | java.lang.NullPointerException: Could not retrieve parameter dataset.fvcom/field_var_bathy_triangle

**Comment by barriern** [comment]
Hi Lily.

My bad. You need to manually open the XML configuration file and add, in the fvcom dataset section, the missing parameter.

This new parameter must be set equal to the name of bathymetry variable **at the center of the triangle**. It is h_center or something alike.

**Comment by lmengel422** [comment]
Hi Nicolas,

Ok, thanks! That works and seemed to help some particles (maybe ~half) to stay at depths below 0. However, the other half still reach above 0 (and max out around 2.7 m). 

Thanks,
Lily

**Comment by barriern** [comment]
Hi Lily.

Ok, it is better than nothing. Particles at depths around 2.7m are at the surface (depth is equals to SSH values).

If I have some extra time, I will dig further into this issue.

Nicolas

**Comment by lmengel422** [comment]
Hi Nicolas,

I realized I should give you a bit more context as to why I am looking at the depths so much. I am trying to utilize the DVM capability, but I get this error after about 9 hours of simulation time:

ichthyop[severe] Index -1 out of bounds for length 11 | java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 11
ichthyop[severe] [Simulation] Initialisation failed

I was thinking perhaps this would be fixed with the depths issue. 

Welcome back from your vacation! :) 
Lily

**Comment by ZC-521** [comment]
Hi ,@lmengel422 
I have seen your conversation with others and I feel that you are professional in Ichthyop!
I've been using this model recently but I'm having some problems in RoMS3D part , I hope you can help me , thanks!
The error is in the following
![微信图片_20231115154902](https://github.com/ichthyop/ichthyop/assets/150895385/39110828-a696-4a8c-b049-80e4e3f1315e)

**Comment by ZC-521** [comment]
Hi,@barriern and @lmengel422 
I have seen your conversation with others and I feel that both of you are professional in Ichthyop!
I've been using this model recently but I'm having some problems in RoMS3D part , I hope you can help me , thanks!
The error is in the following:
![微信图片_20231115154902](https://github.com/ichthyop/ichthyop/assets/150895385/bdb5232a-0077-48fc-80a4-4e511ed132d0)

**Comment by lmengel422** [comment]
Hello,

The backward in time capability is not working in FVCOM. The particle quickly gets out of domain and I don't think it is reading the correct nc files. I have sent you the files to recreate this error.

![Image](https://github.com/user-attachments/assets/9e2b764e-047d-4dac-935f-26ad9937ac26)

Thanks,
Lily
